app:
  name: fake-news-detection
  mode: debug   # debug | full

paths:
  data_raw: C:/Users/User/fake-news-detection-spark/data/raw/News_dataset
  data_processed: data/processed
  models: outputs/models
  reports: outputs/reports

spark:
  master: "local[*]"
  app_name: "FakeNewsSpark"
  driver_memory: "4g"
  executor_memory: "4g"
  shuffle_partitions: 8
  configs:
    spark.sql.adaptive.enabled: "true"
    spark.sql.adaptive.coalescePartitions.enabled: "true"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"
    spark.python.worker.reuse: "true"

pipeline:
  debug_sample_fraction: 0.05
  min_text_length: 30
  cache_clean_data: true
  cache_features: true
